# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 56e7e19c98e3d1e6e7bd82b0ca4c276ce8eff3217cd18707518835d52a93b43f5cc5d24d18353a5b43dbab748eba6bb28fdd75bc71169e77e04e1ae1cf6713c6

test:
  secret_key_base: 8b008b12c7d71c08962224fdbb6c211debff28267b1bb1389de500bc54665ad7c7ce46625c9feaeb2a1aa0ee217f11367e25f5f5a04d491975290f88038cae98

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
